#!/bin/bash

# remove build files
rm -rvf \
aixen \
*.o

# remove generated autotools files
rm -rvf \
aclocal.m4 \
compile \
config.h \
config.h.in \
config.log \
config.status \
configure \
depcomp \
install-sh \
makefile \
makefile.in \
missing \
stamp-h1 \
autom4te.cache
